[font.bold]
family = "FiraMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font Mono"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 2
y = 2
